name: Build and Deploy to Github Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Build site
        run: pnpm run build
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4