  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 18
      cache: 'pnpm'

  - name: Install dependencies
    run: pnpm install

  - name: Build
    run: pnpm run build

  - name: Upload pages artifact
    id: upload-pages-artifact
    uses: actions/upload-pages-artifact@v1
    with:
      path: docs